#     _         _       ____    ____
#    / \   _ __(_) __ _|___ \  |  _ \ _ __ ___
#   / _ \ | '__| |/ _` | __) | | |_) | '__/ _ \
#  / ___ \| |  | | (_| |/ __/  |  __/| | | (_) |
# /_/   \_\_|  |_|\__,_|_____| |_|   |_|  \___/
#
# https://github.com/P3TERX/Docker-Aria2-Pro
#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.

name: Docker images build test

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: 
      - master
    paths:
      - 'rootfs/**'
      - 'Dockerfile'
  schedule:
    - cron: 10 16 * * *

jobs:
  build:
    name: Build test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install buildx
      run: |
        mkdir -vp ~/.docker/cli-plugins/
        wget -nv -O- https://api.github.com/repos/docker/buildx/releases/latest \
        | grep "browser_download_url.*linux-amd64\"" \
        | cut -d '"' -f 4 \
        | wget -nv -O ~/.docker/cli-plugins/docker-buildx -i-
        chmod +x ~/.docker/cli-plugins/docker-buildx

    - name: Set up buildx
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use --name multi-arch-builder

    - name: Available platforms
      run: |
        docker buildx inspect --bootstrap | grep Platforms

    - name: Login to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build test
      env:
        PLATFORMS: linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6
        IMAGE_NAME: p3terx/aria2-pro
        IMAGE_TAG: test
        DOCKERFILE: Dockerfile
        FILE_PATH: .
      run: |
        docker buildx build --push \
          --platform ${PLATFORMS} \
          -t ${IMAGE_NAME}:${IMAGE_TAG} \
          -f ${DOCKERFILE} \
          ${FILE_PATH}
